### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by czhiling** [SimonBiggs/ipython-geant4-linac#1]
Thank you for your work. I think it's a very nice idea to make physicists' life easier.

I am new to docker and trying to install your example on my SUSE linux 13.2.

The first installation was failed due to no enough disk for images. After I managed the disk space, I re-run the instillation command:

`docker run -p 8888:8888 simonbiggs/geant4-examples`

I get following errors:

```
linux-ed6b:~ # docker run -p 8888:8888 simonbiggs/geant4-examples
Unable to find image 'simonbiggs/geant4-examples:latest' locally
Pulling repository simonbiggs/geant4-examples
64574b2d05d3: Error pulling image (latest) from simonbiggs/geant4-examples, endpoint: https://registry-1.docker.io/v1/, Driver devicemapper failed to create ima64574b2d05d3: Error pulling image (latest) from simonbiggs/geant4-examples, Driver devicemapper failed to create image rootfs 511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158: device 511136ea3c5a64f264b78b5433614aec563103b4dFATA[0007] Error pulling image (latest) from simonbiggs/geant4-examples, Driver devicemapper failed to create image rootfs 511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158: device 511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158 already exists 

```

Any advice?

**Comment by SimonBiggs** [comment]
Gday, glad to be of help.

As a first attempt can you try this, `docker rmi 511`. And then try again? If that doesn't work give this "on and off again" approach by removing the containers relevant to this repo. You can do this in two ways. Simple way is to remove all of your containers and try from scratch. This can be done in this way:

```
docker rm $(docker ps -a -q)
docker rmi $(docker images -q)
```

Of course if you don't want to remove all of the containers you can type `docker ps -a` and then individually remove the containers relevant to this with `docker rm`, and then type `docker images` and remove the relevant images with `docker rmi`.

If that fails let me know and I'll see what I can do.

**Comment by czhiling** [comment]
According to your advice, I reset the docker and installed the `ipython-geant4-linac` from scratch successfully. It works like a charm. 

Thank you very much for your help.

**Comment by SimonBiggs** [comment]
Glad to hear :). Let me know if you find it useful.
